---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orchestrator-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator-role-binding
subjects:
- kind: ServiceAccount
  name: orchestrator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io